ecs/node/drain: Fix a bug fails draining if greater than 10 instances
We can specify up to 10 container instances to update state in a single operation.
This constraint is not specified in the API reference, but it returns the following error:
  InvalidParameterException: instanceIds can have at most 10 items.
So we need to divide the list by 10.